### ISSUE TITLE
About Design.md

### ISSUE THREAD

**Issue by Osgood001** [GKDRateIt/front-end#2]
> 设计疑问 1：我们需要为课程/教师分类设计入口页面吗？即我们需要一个页面来单独展示课程，一个页面来单独展示教师吗？

>设计疑问 2：允许对某老师进行评价吗（不与特定课程关联）？

我觉得评价教师不是很好，应该专注于课程本身，不过点击教师后可以出现一个页面，里面给出他上的所有课程和评分，例如 https://icourse.club/teacher/759/

**Comment by LinHeLurking** [comment]
是的，我也倾向于认为不需要单独给教师评分，只要给一个页面可以展示教师的所有课程及其评分即可。
